# Bài tập 1. Phép toán cơ bản với ma trận

In [1]:
import numpy as np

Câu 1

In [ ]:
A = np.array([[2, 1, -1], [0, 1, -4]])
B = np.array([[-2, 1, 0], [-3, 2, 2]])
print(3*A+2*B)

[[ 2  5 -3]
 [-6  7 -8]]


Câu 2

In [ ]:
A = np.array([[2,-5,1],[3,0,-4]])
B = np.array([[1,-2,-3],[0,-1,5]])
C = np.array([[0,1,-2],[1,-1,-1]])
print(3*A+4*B-2*C)

[[ 10 -25  -5]
 [  7  -2  10]]


Câu 3

In [ ]:
A = np.array([[0,0,1],
             [1,1,2],
             [2,2,3],
             [3,3,4]])
B = np.array([[-1,-1],[2,2],[1,1]])
C = np.array([[4],[1]])
print(A@B@C)

[[ 5]
 [15]
 [25]
 [35]]


Câu 4

In [ ]:
A = np.array([[1,3,5],[6,-7,-8]])
AT = np.transpose(A)
print('A^T:\n',AT)
print('(A^T)^T:\n',np.transpose(AT))
print('A(A^T):\n',A@AT)
print('(A^T)A:\n',AT@A)

A^T:
 [[ 1  6]
 [ 3 -7]
 [ 5 -8]]
(A^T)^T:
 [[ 1  3  5]
 [ 6 -7 -8]]
A(A^T):
 [[ 35 -55]
 [-55 149]]
(A^T)A:
 [[ 37 -39 -43]
 [-39  58  71]
 [-43  71  89]]


Câu 5

In [ ]:
A = np.array([[1,2],[3,-4]])
B = np.array([[5,0],[-6,7]])
print('(AB)^T:\n',np.transpose(A@B))
print('(A^T)(B^T):\n',np.transpose(B@A)) #= (np.transpose(A))@(np.transpose(B)))  
print('(B^T)(A^T):\n',np.transpose(A@B)) #= (np.transpose(B))@(np.transpose(A)))

(AB)^T:
 [[ -7  39]
 [ 14 -28]]
(A^T)(B^T):
 [[  5  15]
 [ 10 -40]]
(B^T)(A^T):
 [[ -7  39]
 [ 14 -28]]


Câu 6

In [ ]:
A = np.array([[2,0,0],[3,-1,0],[4,-2,5]])
B = np.array([[2,0],[1,-3],[4,5]])
C = A@B
print('AB:\n',C)
print('(A^T)A:\n',A@(np.transpose(A)))
print('AB-3B:\n',C-3*B)

AB:
 [[ 4  0]
 [ 5  3]
 [26 31]]
(A^T)A:
 [[ 4  6  8]
 [ 6 10 14]
 [ 8 14 45]]
AB-3B:
 [[-2  0]
 [ 2 12]
 [14 16]]


Câu 7

In [ ]:
A = np.array([[1,2,3,4],
              [2,5,4,7],
              [3,7,8,12],
              [4,8,14,19]])
print('A^-1:\n',np.linalg.inv(A))

A^-1:
 [[10.  7. -9.  1.]
 [-2. -3.  4. -1.]
 [ 1. -3.  3. -1.]
 [-2.  2. -2.  1.]]


Câu 8

In [7]:
from numpy.linalg import matrix_power
A = np.array([[0,1,0],[0,0,1],[0,0,0]])
AT = np.transpose(A)
print('A(A^T):\n',A@AT)
print('(A^T)A:\n',AT@A)
print('A^2:\n',matrix_power(A,2))
print('A^3:\n',matrix_power(A,3))

A(A^T):
 [[1 0 0]
 [0 1 0]
 [0 0 0]]
(A^T)A:
 [[0 0 0]
 [0 1 0]
 [0 0 1]]
A^2:
 [[0 0 1]
 [0 0 0]
 [0 0 0]]
A^3:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [8]:
from numpy.linalg import matrix_power
A = [[1,-3],[2,5]]
print(matrix_power(A,2))
print(np.square(A))

[[ -5 -18]
 [ 12  19]]
[[ 1  9]
 [ 4 25]]


Câu 9

In [ ]:
A = np.array([[1,0,-1],[-2,1,4],[3,2,2]])
B = np.array([[4,-1,2],[-6,7,-3],[1,0,-8]])
C = np.array([[3,-2,-1],[-4,0,9],[2,-7,5]])
print('AB-(A^T)C:\n',A@B-(np.transpose(A)@C))

AB-(A^T)C:
 [[-14  22  14]
 [-10  23 -58]
 [ 17  23 -63]]


Câu 10

In [ ]:
A = np.array([[1,3],[-1,2],[3,4]])
B = np.array([[0,1],[3,2],[-2,3]])
C = np.array([[2,-3],[1,2],[4,-1]])
print('A+(B+C):\n',A+B+C)
print('(A+B)+C:\n',A+B+C)
print('3A:\n',3*A)
print('A^T:\n',np.transpose(A))
print('B^T:\n',np.transpose(B))
print('C^T:\n',np.transpose(C))

A+(B+C):
 [[3 1]
 [3 6]
 [5 6]]
(A+B)+C:
 [[3 1]
 [3 6]
 [5 6]]
3A:
 [[ 3  9]
 [-3  6]
 [ 9 12]]
A^T:
 [[ 1 -1  3]
 [ 3  2  4]]
B^T:
 [[ 0  3 -2]
 [ 1  2  3]]
C^T:
 [[ 2  1  4]
 [-3  2 -1]]


# Bài tập 2. Đa thức ma trận

Câu 1

In [9]:
A = np.array([[1,-2,3],[2,-3,1],[3,-5,2]])
f_a = 3*matrix_power(A,2) - 2*A + 5
print(f_a) 

[[ 21 -24  20]
 [ -2  11  18]
 [ -4  12  25]]


Câu 2

In [19]:
A = np.array([[2,2],[3,-1]])
f_a = matrix_power(A,3) - 3*matrix_power(A,2) - 2*A + 4
print(f_a)

[[ -4  12]
 [ 16 -16]]


Câu 3

In [20]:
A = np.array([[1,1],[0,1]])
f_a = matrix_power(A,3) -3*A + 2*matrix_power(A,-1)
print(f_a)

[[ 0. -2.]
 [ 0.  0.]]


Câu 4

In [22]:
A = np.array([[0,1,1],[1,0,1],[1,1,0]])
f_a = matrix_power((matrix_power(A,2)-1),-1) - matrix_power((matrix_power(A,2)+1),-1)
print(f_a)

[[0.28571429 0.28571429 0.28571429]
 [0.28571429 0.28571429 0.28571429]
 [0.28571429 0.28571429 0.28571429]]


# Bài tập 3. Định thức của ma trận


Câu 1:

In [29]:
A = np.array([[1+2**0.5,2-3**0.5],[2+3**0.5,1-2**0.5]])
print('det(A) =',round(np.linalg.det(A)))

det(A) = -2


Câu 2:

In [30]:
A = np.array([[1,2,-3,1],
              [0,2,4,-2],
              [1,3,0,-4],
              [2,0,-1,5]])
print('det(A) =', round(np.linalg.det(A)))

det(A) = 102


Câu 3:

In [31]:
A = np.array([[3,-1,4,2],
              [5,2,0,1],
              [0,2,1,-3],
              [6,-2,9,8]])
print('det(A) =', round(np.linalg.det(A)))

det(A) = 223


Câu 4: 

In [32]:
A = np.array([[1, 0, 2, 0, 3, 0],
              [5, 1, 4, 2, 7, 3],
              [1, 0, 4, 0, 9, 0],
              [8, 1, 5, 3, 7, 6],
              [1, 0, 8, 0, 27, 0],
              [9, 1, 5, 4, 3, 10]])
print('det(A) =', round(np.linalg.det(A)))

det(A) = 12


Câu 5: 

In [33]:
A = np.array([[-4, 0, 2, -1, 0],
              [1, 3, -3, -1, 4],
              [2, 0, 1, 3, 0],
              [-2, 1, -3, -1, 2],
              [1, -5, 1, 0, 5]])
print('det(A) =', round(np.linalg.det(A)))

det(A) = -1069
